In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import itertools

In [2]:
yan_d=pd.read_csv('count_yan.csv')
yan1_d=pd.read_csv('count_yan.csv')
dp_d = pd.read_csv('dp_yan.csv')
sim_d = pd.read_csv('sim_yan.csv')
yan=yan_d.values
yan_imputed=yan1_d.values
dp=dp_d.values
sim=sim_d.values
nrow=len(yan)
ncol=len(yan[0])
nr=len(sim)

In [3]:
print(nrow)
print(ncol)
print(nr)

4725
90
90


In [4]:
yan

array([[8.54228942, 8.27597732, 8.19926718, ..., 8.64547233, 8.85365244,
        8.70038235],
       [3.41937881, 3.91804988, 3.6672635 , ..., 0.        , 0.        ,
        1.97193964],
       [1.52374329, 2.01205696, 2.37058224, ..., 0.75228527, 1.08434066,
        3.19125934],
       ...,
       [5.53004205, 5.17238454, 5.13730345, ..., 7.51972176, 6.777161  ,
        6.56314295],
       [4.47738062, 5.27071083, 5.24442072, ..., 1.23803982, 1.75793023,
        3.79082251],
       [4.85515285, 4.81643406, 4.8303336 , ..., 4.4693775 , 4.79607402,
        3.93905471]])

In [5]:
yan_imputed

array([[8.54228942, 8.27597732, 8.19926718, ..., 8.64547233, 8.85365244,
        8.70038235],
       [3.41937881, 3.91804988, 3.6672635 , ..., 0.        , 0.        ,
        1.97193964],
       [1.52374329, 2.01205696, 2.37058224, ..., 0.75228527, 1.08434066,
        3.19125934],
       ...,
       [5.53004205, 5.17238454, 5.13730345, ..., 7.51972176, 6.777161  ,
        6.56314295],
       [4.47738062, 5.27071083, 5.24442072, ..., 1.23803982, 1.75793023,
        3.79082251],
       [4.85515285, 4.81643406, 4.8303336 , ..., 4.4693775 , 4.79607402,
        3.93905471]])

In [6]:
import numpy as np
imp=np.empty((nrow,ncol))
imp

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
impute=[]
impute=list()
for i, j in itertools.product(range(0,nrow), range(0,ncol)):
    if dp[i][j]>0.75:
        zval=yan[i][j]
        temp=[]
        temp=list()
        for k in range(nr):
            if sim[j][k]>0.9:
                val=yan[i][k]
                temp.append([i,k,val])
        ##regression
        t=np.array(temp)
        n=len(t)
        if(n==0):
            imp[i][j]=np.nan
        if(1<=n<5):
            X=t[:,1]
            y=t[:,2]
            m=round(np.average(y))
            impute.append([i,j,zval,m])
            imp[i][j]=m
            yan_imputed[i][j]=m
        if(n>=5):
            X=t[:,1]
            y=t[:,2]
            ##Regression
            
            from sklearn.model_selection import train_test_split
            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
            X_test=np.append(X_test,j)
            y_test=np.append(y_test,zval)
            
            # Fitting Decision Tree Regression to the dataset
            from sklearn.tree import DecisionTreeRegressor
            regressor = DecisionTreeRegressor(random_state=0)
            regressor.fit(X_train.reshape(-1,1), y_train.reshape(-1,1))
            y_pred = regressor.predict(X_test.reshape(-1,1))
            
            df = pd.DataFrame({'Cell_No':X_test.reshape(-1),'Real_Values':y_test.reshape(-1), 'Imputed_Values':y_pred.reshape(-1)})
            m=df.loc[df['Cell_No'] == j, 'Imputed_Values'].squeeze()
            impute.append([i,j,zval,m])
            imp[i][j]=m
            yan_imputed[i][j]=m
    else:
        imp[i][j]=np.nan

In [8]:
imp

array([[      nan,       nan,       nan, ...,       nan,       nan,
              nan],
       [      nan,       nan,       nan, ..., 0.5432382,       nan,
              nan],
       [      nan,       nan,       nan, ...,       nan,       nan,
              nan],
       ...,
       [      nan,       nan,       nan, ...,       nan,       nan,
              nan],
       [      nan,       nan,       nan, ...,       nan,       nan,
              nan],
       [      nan,       nan,       nan, ...,       nan,       nan,
              nan]])

In [9]:
impute

[[1, 51, 0.0, 3.6804357798668],
 [1, 76, 0.0, 0.0],
 [1, 80, 0.0, 0.0],
 [1, 85, 0.0, 0.0],
 [1, 87, 0.0, 0.543238199287998],
 [6, 54, 0.0, 1.80604985436805],
 [6, 55, 0.0, 0.0],
 [6, 56, 0.0, 0.922568052689295],
 [6, 61, 0.0, 2.3409714420504],
 [6, 62, 0.0, 0.0],
 [6, 63, 0.0, 0.0],
 [6, 64, 0.0, 0.0],
 [6, 65, 0.0, 0.0],
 [6, 66, 0.0, 0.0],
 [6, 67, 0.0, 0.0],
 [6, 68, 0.0, 0.0],
 [6, 69, 0.0, 0.0],
 [6, 71, 0.0, 3.58361028479067],
 [6, 72, 0.0, 0.0],
 [6, 73, 0.0, 0.0],
 [6, 74, 0.0, 0.0],
 [6, 75, 0.0, 0.0],
 [6, 76, 0.0, 0.0],
 [6, 77, 0.0, 0.0],
 [6, 78, 0.0, 0.0],
 [6, 79, 0.0, 0.0],
 [6, 80, 0.0, 0.0],
 [6, 81, 0.0, 0.0],
 [6, 82, 0.0, 0.0],
 [6, 83, 0.0, 0.0],
 [6, 84, 0.0, 0.0],
 [6, 85, 0.0, 0.0],
 [6, 86, 0.0, 0.0],
 [6, 87, 0.0, 0.0],
 [6, 88, 0.0, 0.0],
 [6, 89, 0.0, 0.0],
 [14, 45, 0.0, 4.42180635166307],
 [14, 49, 0.0, 1.65006505870246],
 [14, 55, 0.0, 1.75726086783571],
 [14, 61, 0.0, 1.34802506312807],
 [14, 62, 0.0, 0.0],
 [14, 63, 0.0, 0.0],
 [14, 64, 0.0, 0.0],
 [1

In [10]:
yan_imputed

array([[8.54228942, 8.27597732, 8.19926718, ..., 8.64547233, 8.85365244,
        8.70038235],
       [3.41937881, 3.91804988, 3.6672635 , ..., 0.5432382 , 0.        ,
        1.97193964],
       [1.52374329, 2.01205696, 2.37058224, ..., 0.75228527, 1.08434066,
        3.19125934],
       ...,
       [5.53004205, 5.17238454, 5.13730345, ..., 7.51972176, 6.777161  ,
        6.56314295],
       [4.47738062, 5.27071083, 5.24442072, ..., 1.23803982, 1.75793023,
        3.79082251],
       [4.85515285, 4.81643406, 4.8303336 , ..., 4.4693775 , 4.79607402,
        3.93905471]])

In [13]:
yan[1][87]

0.0

In [14]:
yan_imputed[1][87]

0.543238199287998

In [15]:
yan_imputed_t=np.transpose(yan_imputed)

In [18]:
yan_imputed[1][87]

0.543238199287998

In [19]:
yan_imputed_t.shape

(90, 4725)

In [20]:
import csv

with open("yan_imputed.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(yan_imputed)

In [21]:
import csv

with open("yan_imputed_t.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(yan_imputed_t)